SankethBK/diaryvault

lib/core/pages/settings_page.dart
lib/core/widgets/share_with_friends.dart
pubspec.yaml

closses issue #15 
Added share with friends option in settings screeen.
On pressing , it will show options to share the link in various social media.
For reference I've attached the photo.

Added share with friends option

---

lib/core/pages/settings_page.dart
lib/core/widgets/auto_save_enable.dart
lib/features/auth/core/constants.dart
lib/features/auth/data/models/user_config_model.dart
lib/features/notes/presentation/bloc/notes/notes_bloc.dart
lib/features/notes/presentation/bloc/notes/notes_event.dart
lib/features/notes/presentation/bloc/notes/notes_state.dart
lib/features/notes/presentation/bloc/notes_fetch/notes_fetch_cubit.dart
lib/features/notes/presentation/pages/note_create_page.dart

This Feature will auto save note after X seconds, and only at the time of exit or save it will fetch notes. 
We are emiting the AutoSaveNote event with a timer of "x" seconds (currently it is specified as 10 seconds in code).
If Note is new, and auto save note is triggered multiple time. 
- First time AutoSaveNote event triggered it will save the note. 
- Next time it is triggered, it will update the note. 
Used Timer.periodic to emit AutoSaveNote event.
Now user can go to setting page and enable or disable the auto save functionality. 
- Closes #29

auto save notes #29

---

lib/features/auth/presentation/widgets/security_settings.dart
pubspec.lock
pubspec.yaml

#39 - added accordion for security settings.

---

lib/core/network/network_info.dart
lib/features/auth/data/datasources/local data sources/local_data_source.dart
lib/features/auth/data/repositories/user_config_repository.dart
lib/features/auth/presentation/pages/auth_page.dart
lib/features/auth/presentation/widgets/password_reset_popup.dart
lib/features/auth/presentation/widgets/sign_up_form.dart
lib/features/notes/presentation/widgets/read_only_editor.dart
lib/features/sync/data/datasources/dropbox_sync_client.dart
lib/features/sync/presentation/widgets/sync_source_dropdown.dart
lib/main.dart

Removed unused imports from the app.

Remove unused packages.

---

lib/features/notes/presentation/pages/note_read_only_page.dart
lib/features/notes/presentation/widgets/read_notes.dart

solves: #60 
Updated the file by adding pause button functionality and created read_notes.dart in widgets directory

Updated the file by adding pause button functionality and created read_notes.dart in widgets directory.

---

lib/core/widgets/auto_save_enable.dart

add subtitle to Enable Auto Save SwitchListTile "Automatically saves your notes after every 10 seconds"
- Related Issue #59 
- Closes #59

add subtitle to Enable Auto Save SwitchListTile

---

lib/features/notes/presentation/widgets/note_read_button.dart

Increase volume for text to speech

---

.gitignore

Ignore generated plugin files

---

.env
integration_test/test_guest_login.dart
integration_test/test_note_deletion.dart
integration_test/test_note_updation.dart
lib/features/sync/data/datasources/dropbox_sync_client.dart
lib/features/sync/presentation/widgets/dropbox_user_info.dart
lib/main.dart
macos/Flutter/GeneratedPluginRegistrant.swift
packages/stateless_dropbox_client/lib/stateless_dropbox_client.dart
pubspec.lock
pubspec.yaml

Pull dropbox client token on first signin from proxy server
- Closes #

Retrieve dropbox token from proxy

---

lib/app/themes/coral_bubble_theme.dart
lib/app/themes/cosmic_theme.dart
lib/app/themes/lush_green_theme.dart
lib/app/themes/plain_dark.dart
lib/core/dependency_injection/injection_container.dart
lib/core/pages/home_page.dart
lib/core/widgets/home_page_app_bar.dart
lib/features/auth/core/constants.dart
lib/features/auth/data/models/user_config_model.dart
lib/features/notes/presentation/bloc/notes_fetch/notes_fetch_cubit.dart
lib/features/notes/presentation/bloc/notes_fetch/notes_fetch_state.dart
lib/generated/intl/messages_all.dart
lib/generated/intl/messages_en.dart
lib/generated/intl/messages_gu.dart
lib/generated/l10n.dart
lib/l10n/intl_en.arb
pubspec.yaml

Notes can be sorted based on latest first, oldest first or alphabetical order
- Related Issue # https://github.com/SankethBK/diaryvault/issues/28
- Closes # https://github.com/SankethBK/diaryvault/issues/28

Customizable_sort_order

---

pubspec.yaml

Update version 2.1.4

---

lib/app/themes/font.dart
lib/core/pages/settings_page.dart
lib/core/widgets/font_customization.dart
lib/features/auth/core/constants.dart
lib/features/auth/data/models/user_config_model.dart
lib/features/auth/data/repositories/user_config_repository.dart
lib/features/notes/presentation/pages/note_read_only_page.dart
lib/features/notes/presentation/widgets/note_preview_card.dart
lib/features/notes/presentation/widgets/note_title_input_field.dart
lib/features/notes/presentation/widgets/read_only_editor.dart
lib/features/notes/presentation/widgets/rich_text_editor.dart

Add Font size and family customization

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

Added distributionSha256Sum

---

pubspec.yaml

Updated version 2.1.5

---

pubspec.yaml

Update version 2.1.6

---

README.md
lib/generated/intl/messages_pt.dart
lib/l10n/intl_pt.arb

added remining strings for Portuguese

---

pubspec.yaml

Update version 2.1.7

---

CONTRIBUTING.md

- Related Issue #153
- Closes #153
This would be only in-case your flutter version is the stable version cloned from the GitHub flutter repository. In that case the expected output of commands is evident in the following image:

Adding version issue to contributing.md

---

pubspec.yaml

Update version 2.1.8

---

lib/features/auth/presentation/widgets/sign_in_form.dart

Fix missing translation and inconsistency.
- closes #171

fix: use submit translation on signinforms submit button

---

pubspec.yaml

Update version 2.1.9

---

lib/generated/intl/messages_pl.dart
lib/l10n/intl_pl.arb

Adding Polish translations for newly added PIN authentication feature
- Related Issue #75

add missing Polish translations for PINcode related vocabulary

---

README.md

Add missing languages to the table (Spanish, Polish and Telugu, also added English as primary).  
Additionally sorted the table alphabetically.  
I set the complete/incomplete status for the added languages by a rough comparison of number of lines in the given file to the English file.  
If the file had ~80%+ of the amount of lines in English, i considered it to complete (seamed reasonable considering other languages in the table)  
Completion percentages for each language:
ar: 62.9%
de: 89.52%
en: 100.0%
es: 89.52%
fi: 76.61%
fr: 89.52%
gu: 76.61%
he: 62.9%
hi: 89.52%
id: 79.03%
kn: 62.9%
pa: 62.9%
pl: 90.32% (mind PR #177 brings this back to 100%)
pt: 89.52%
sw: 62.9%
te: 90.32%
zh: 89.52%

add missing languages and sort the language table in main README

---

packages/flutter_quill/flutter_quill_extensions/lib/embeds/audio_player.dart

- Closes #
Before and after fix
<div>
</div>

Fix text overflow issue for audio player

---

pubspec.yaml

Update version 2.2.1

---

android/app/build.gradle

Fix package name

---

lib/features/notes/data/datasources/local data sources/local_data_source.dart
lib/features/notes/data/datasources/local data sources/local_data_source_template.dart
lib/features/notes/data/repositories/notes_repository.dart
lib/features/notes/domain/repositories/notes_repository.dart
lib/features/notes/presentation/widgets/tag_text_input.dart

Tag names are tedious to type for every note, so added autocomplete which displays existing tags in a dropdown
- Closes #

Autocomplete tag names

---

android/app/google-services.json
lib/core/pages/settings_page.dart
lib/core/widgets/settings_tile.dart
lib/features/notes/presentation/widgets/daily_reminders.dart
lib/features/notes/presentation/widgets/export_notes.dart
packages/simple_accordion/lib/widgets/AccordionItem.dart

Fix uneven spacing in settings page

---

pubspec.yaml

Update version 2.2.2

---

android/app/build.gradle
lib/features/sync/data/datasources/dropbox_sync_client.dart
packages/stateless_dropbox_client/lib/stateless_dropbox_client.dart

Change dropbox app

---

pubspec.yaml

Update version 2.2.3

---

.gitignore
lib/features/notes/presentation/pages/note_create_page.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

Added code to exit the note page after saving. The in-app review modal is shown before exiting. Additionally, a log file was added to capture any errors while fetching the app review popup.
- Related Issue #216
- Closes #216 
- Was unable to test it as it requires the app to be published on the Playstore to work.

In-App Review Modal

---

.github/workflows/greetings.yml

Have designed a workflow which will greet user on their email and in the issue raising chat for raising a issue or PR
Please approve my PR @SankethBK  with labels assigned

Add Automated Greeting Workflow 

---

pubspec.yaml

Update version 2.2.4

---

lib/features/notes/presentation/pages/note_create_page.dart
lib/features/sync/presentation/widgets/sync_settings.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

Revert in app review for FOSS builds

---

.github/workflows/build_apk.yml

Add workflow to build and attach APK to release

---

pubspec.yaml

Update Version 2.2.5

---

lib/core/pages/settings_details.dart
lib/core/widgets/language_dropdown.dart

Fix tile spacing

---

pubspec.yaml

Update version 2.2.6

---

lib/generated/intl/messages_pl.dart
lib/l10n/intl_pl.arb

Updated the Polish translation to be up to date with the English one. Changes are releted mostly in option screen, like Security option, Reminders, Modify Theme, Fonts and Language and Import and Export Notes. In selecting audio, there were also few missing translations. Deleted also in Export to PDF an annotation (beta), following the English translation
- Related Issue #212 
| In options | In selecting audio | In exporting notes |
|        :---:     |            :--:             |               :---:           |
| ![sc1-down](https://github.com/user-attachments/assets/7839d178-1d95-4dd1-9767-3b7ffdf1df8b) | ![sc2-down](https://github.com/user-attachments/assets/de6e2027-ede3-438a-b149-60eaf7955ad2) | ![sc3-down](https://github.com/user-attachments/assets/73861ca4-67f7-4ea6-bdc3-0a313d174 …

update missing Polish translation

---

lib/features/notes/data/repositories/export_notes_repository.dart

- Related Issue #234 
- Closes #234 

Pdf-image-fix

---

pubspec.yaml

Update version 2.2.7

---

lib/core/widgets/settings_tile.dart

fix settings font clipping

---

assets/logo/file_export.svg
lib/core/widgets/home_page_app_bar.dart
lib/features/notes/data/datasources/local data sources/local_data_source.dart
lib/features/notes/data/datasources/local data sources/local_data_source_template.dart
lib/features/notes/data/repositories/export_notes_repository.dart
lib/features/notes/data/repositories/notes_repository.dart
lib/features/notes/domain/repositories/notes_repository.dart
pubspec.lock
pubspec.yaml

Export Selected Notes

---

pubspec.yaml

Update version 2.2.8

---

pubspec.yaml

Version Number updatde to 2.2.9+25

---

lib/app/themes/twilight_gold_theme.dart

Add border for textbox

---

android/app/build.gradle

upgrade target api version

---

.github/workflows/README.md
.github/workflows/build_and_release_alternative.yml
.github/workflows/build_apk.yml

- Add github action to build apk
- Fixes #265

add workflows for apk build
